from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    OrderViewSet,
    OrderItemViewSet,
    WaiterOrderViewSet,
    ReservationViewSet,
    TopCustomersReportView,
    CouponViewSet,
    FeedbackCreateAPIView
)

# Create a router instance to handle ViewSets
router = DefaultRouter()

# Register the primary viewsets for the core models
router.register(r'orders', OrderViewSet, basename='order')
router.register(r'order-items', OrderItemViewSet, basename='order-item')
router.register(r'reservations', ReservationViewSet, basename='reservation')
router.register(r'coupons', CouponViewSet, basename='coupon')

# Register a separate viewset for the waiter-specific orders
router.register(r'waiter-orders', WaiterOrderViewSet, basename='waiter-order')

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
    # Add a separate path for the APIView report
    path('reports/top-customers/', TopCustomersReportView.as_view(), name='top-customers-report'),
    # Path for creating customer feedback
    path('feedback/', FeedbackCreateAPIView.as_view(), name='feedback-create'),
]
